genimage: support IMAGE_NAME_SUFFIX
pengutronix/meta-ptx pull request #123
Opened 2023-12-12 10:13 UTC by Emantor

Since nanbield [1], IMAGE_NAME and IMAGE_LINK_NAME include the IMAGE_NAME_SUFFIX, which means that the rootfs files gain an additional .rootfs suffix. Add support for this in genimage.

[1]: https://docs.yoctoproject.org/4.3.1/migration-guides/migration-4.3.html#output-file-naming-changes

2023-12-12 10:43 UTC, rohieb commented
For refrerence, the default is set in [`poky/meta/classes-recipe/image-artifact-names.bbclass`](https://git.yoctoproject.org/poky/tree/meta/classes-recipe/image-artifact-names.bbclass#n34).

2023-12-12 10:44 UTC, rohieb approved these changes

2023-12-12 10:54 UTC, Bastian-Krause requested changes
The functional change looks good to me.

`GENIMAGE_ROOTFS_IMAGE` and `GENIMAGE_ROOTFS_IMAGE_FSTYPE` are documented. We should do the same for `GENIMAGE_ROOTFS_IMAGE_SUFFIX`, maybe with @rohieb's link?

We don't have a mickledore branch, yet. That means mickledore users currently stick to master. This change will break their rootfs unpacking, right? Maybe add a mickledore branch before merging this?

2023-12-12 11:15 UTC, Emantor commented
- pushed a mickledore branch
- added a commit which removes mickledore from layerseries-compat
- added documentation for the new variable

2023-12-12 11:43 UTC, Bastian-Krause commented on classes-recipe/genimage.bbclass
> +# `GENGIMAGE_ROOTFS_IMAGE_SUFFIX`.
```suggestion
# `GENIMAGE_ROOTFS_IMAGE_SUFFIX`.
```

2023-12-12 12:26 UTC, Emantor commented
Fixed the typo.

2023-12-12 12:43 UTC, Bastian-Krause approved these changes

2024-01-05 13:55 UTC, ejoerns commented on classes-recipe/genimage.bbclass
> +GENIMAGE_ROOTFS_IMAGE_SUFFIX ?= "rootfs"
Shouldn't this default to `IMAGE_NAME_SUFFIX`?

2024-04-21 22:07 UTC, ejoerns commented
Rebased on master.

2024-04-21 22:36 UTC, ejoerns commented
This is now reworked to define

    GENIMAGE_ROOTFS_IMAGE_SUFFIX ?= "${IMAGE_NAME_SUFFIX}"

I'm not fully sure if it needs a variable or if we can just rely directly on `IMAGE_NAME_SUFFIX` here.

Note that the same change would be useful for `IMAGE_MACHINE_SUFFIX` then.

2024-04-30 10:42 UTC, Bastian-Krause approved these changes
LGTM. Haven't tested it because I don't have a recent Yocto BSP using genimage at hand.

2024-04-30 10:55 UTC, merged